[package]
name = "tpt-yard-hull"
description = "Hull construction and block management for sea shipyards."
keywords = ["hull", "block-division", "erection", "shipbuilding", "shipyard"]
categories = ["science", "simulation"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tpt-yard-core = { workspace = true }
tpt-yard-blocks = { workspace = true }
