[package]
name = "rotating-habitat-construction"
description = "TPT Shipyard example: rotating-habitat-construction"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tpt-yard-core = { workspace = true }
tpt-yard-habitat = { workspace = true }
tpt-yard-space-structural = { workspace = true }

[lints]
workspace = true
