[package]
name = "drydock-flooding-sequence"
description = "TPT Shipyard example: drydock-flooding-sequence"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tpt-yard-core = { workspace = true }
tpt-yard-drydock = { workspace = true }
tpt-yard-launch = { workspace = true }
tpt-yard-weight = { workspace = true }
