[package]
name = "tpt-yard-orbital-assembly"
description = "Orbital assembly planning and simulation for space structures."
keywords = ["orbital-assembly", "space", "truss", "robotics", "simulation"]
categories = ["aerospace", "aerospace::simulation", "science", "simulation"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tpt-yard-core = { workspace = true }
tpt-yard-robotic-assembly = { workspace = true }

[lints]
workspace = true
