[package]
name = "orbital-station-truss"
description = "TPT Shipyard example: orbital-station-truss"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tpt-yard-core = { workspace = true }
tpt-yard-orbital-assembly = { workspace = true }
tpt-yard-robotic-assembly = { workspace = true }
