//! `tpt-yard` — the command-line front end for tpt-shipyard.
//!
//! Subcommands (review 7F CLI item, with the 7H end-to-end `plan`):
//!
//! - `validate FILE.json` — load a vessel project (or hull manifest) and
//!   report every inconsistency; exit 1 on failure.
//! - `plan MANIFEST.json` — the end-to-end construction plan for a hull
//!   manifest: block division → erection order → lift checks → schedule →
//!   critical path, one report.
//! - `schedule FILE.json` — CPM critical path and resource-levelling for a
//!   vessel project's activities.
//! - `report FILE.json` — weight/CoG/structural summary for a project.
//! - `new <sea|space> [NAME]` — print a scaffolded project JSON built from
//!   the workspace templates.
//!
//! Every command takes `--json` to emit machine-readable output.

use std::process::ExitCode;

use tpt_yard_core::{json::Value, MassProperties, Vector3};

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (json_mode, args) = split_flag(&args, "--json");
    match run(&args, json_mode) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            eprintln!("usage: tpt-yard <validate|plan|schedule|report|new> [--json] ...");
            ExitCode::FAILURE
        }
    }
}

fn split_flag<'a>(args: &'a [String], flag: &str) -> (bool, Vec<&'a str>) {
    let mut json = false;
    let mut rest = Vec::new();
    for a in args {
        if a == flag {
            json = true;
        } else {
            rest.push(a.as_str());
        }
    }
    (json, rest)
}

fn run(args: &[&str], json_mode: bool) -> Result<(), String> {
    let (cmd, rest) = args.split_first().ok_or("missing subcommand")?;
    match *cmd {
        "validate" => validate(rest.first().ok_or("validate needs a file path")?),
        "plan" => plan(rest.first().ok_or("plan needs a hull manifest path")?, json_mode),
        "schedule" => schedule(rest.first().ok_or("schedule needs a file path")?, json_mode),
        "report" => report(rest.first().ok_or("report needs a file path")?, json_mode),
        "new" => new(rest, json_mode),
        "html-report" => {
            let (out, rest): (String, &[&str]) = if rest.first() == Some(&"--out") {
                (
                    rest.get(1).copied().ok_or("--out needs a path")?.to_string(),
                    rest.get(2..).unwrap_or_default(),
                )
            } else {
                ("report.html".to_string(), rest)
            };
            html_report(rest.first().ok_or("html-report needs a project path")?, &out)
        }
        other => Err(format!("unknown subcommand '{other}'")),
    }
}

/// The HTML calculation-package report (review 7H roadmap item: "report
/// generator — HTML/PDF calculation package per phase").
fn html_report(path: &str, out_path: &str) -> Result<(), String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let v = tpt_yard_core::json::Value::parse(&text).map_err(|e| format!("{path}: {e}"))?;
    let project = tpt_yard_core::VesselProject::from_json_value(&v)
        .map_err(|e| format!("{path}: {e}"))?;
    let twin = tpt_yard::tpt_yard_digital_twin::DigitalTwin::new(project);
    let report = twin.weight_model().weight_report();
    let check = twin.structural_check();

    let mut rows = String::new();
    for (group, kg) in &report.by_group {
        rows.push_str(&format!(
            "<tr><td>{group}</td><td>{kg:.0}</td></tr>
"
        ));
    }
    let mut phase_rows = String::new();
    for phase in &twin.vessel.build_phases {
        phase_rows.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{:.0}</td><td>{}</td></tr>
",
            phase.id.0,
            phase.name,
            phase.weight_state.design_kg,
            phase.activities.len(),
        ));
    }
    let html = format!(
        r#"<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>tpt-shipyard report — {name}</title>
<style>
 body {{ font-family: system-ui, sans-serif; margin: 2rem; color: #16222f; }}
 table {{ border-collapse: collapse; margin: 1rem 0; }}
 td, th {{ border: 1px solid #b8c4d0; padding: 4px 12px; }}
 th {{ background: #eef3f8; text-align: left; }}
 .pass {{ color: #157a3e; font-weight: 600; }}
 .fail {{ color: #b3261e; font-weight: 600; }}
 h1 {{ border-bottom: 2px solid #2c6bed; padding-bottom: .3rem; }}
</style></head><body>
<h1>Construction report — {name}</h1>
<p>{phases} build phases, {acts} activities · generated by tpt-yard-cli</p>
<h2>Weights</h2>
<table>
<tr><th>Design (kg)</th><th>Best estimate (kg)</th><th>Growth margin (kg)</th></tr>
<tr><td>{design:.0}</td><td>{est:.0}</td><td>{margin:.0}</td></tr>
</table>
<h2>By group</h2>
<table><tr><th>Group</th><th>kg</th></tr>
{rows}</table>
<h2>Phases</h2>
<table><tr><th>#</th><th>Name</th><th>Design kg</th><th>Activities</th></tr>
{phase_rows}</table>
<h2>Structural check (start state)</h2>
<p class="{cls}">{verdict}</p>
<p>Support reactions and full per-phase FEM: run the structural crate per phase
(roadmap — per-phase HTML sections).</p>
</body></html>
"#,
        name = twin.vessel.name,
        phases = twin.vessel.build_phases.len(),
        acts = twin
            .vessel
            .build_phases
            .iter()
            .map(|p| p.activities.len())
            .sum::<usize>(),
        design = report.design_weight_kg,
        est = report.total_weight_kg,
        margin = report.margin_kg,
        rows = rows,
        phase_rows = phase_rows,
        cls = if check.passed { "pass" } else { "fail" },
        verdict = if check.passed { "PASSED" } else { "FAILED" },
    );
    std::fs::write(out_path, html).map_err(|e| format!("writing {out_path}: {e}"))?;
    println!("HTML report written to {out_path}");
    Ok(())
}

// ---------------------------------------------------------------- validate

fn validate(path: &str) -> Result<(), String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let v = Value::parse(&text).map_err(|e| format!("{path}: {e}"))?;
    if v.get("build_phases").is_some() {
        let project = tpt_yard_core::VesselProject::from_json_value(&v)
            .map_err(|e| format!("{path}: {e}"))?;
        let acts: usize = project
            .build_phases
            .iter()
            .map(|p| p.activities.len())
            .sum();
        println!(
            "OK: project '{}' ({} phases, {acts} activities) passes validation",
            project.name,
            project.build_phases.len()
        );
    } else {
        // Hull manifest: validate the shape the planner consumes.
        let num = |o: &Value, k: &str| {
            o.get(k).and_then(|n| n.as_f64()).ok_or(format!("manifest: '{k}' missing or not a number"))
        };
        let hull = v.get("hull").ok_or("manifest: 'hull' section missing")?;
        for k in ["loa_m", "boa_m", "depth_m", "areal_density_kg_m2", "depth_bands"] {
            num(hull, k)?;
        }
        let yard = v
            .get("yard_capabilities")
            .ok_or("manifest: 'yard_capabilities' section missing")?;
        num(yard, "crane_capacity_kn")?;
        println!("OK: hull manifest '{path}' is well-formed");
    }
    Ok(())
}

// -------------------------------------------------------------------- plan

/// The end-to-end plan (7H): block division → erection order → lift checks
/// → schedule → critical path, one report.
fn plan(path: &str, json_mode: bool) -> Result<(), String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let v = Value::parse(&text).map_err(|e| format!("{path}: {e}"))?;
    let num = |o: &Value, k: &str| {
        o.get(k)
            .and_then(|n| n.as_f64())
            .ok_or(format!("manifest: '{k}' missing or not a number"))
    };

    let hull_v = v.get("hull").ok_or("manifest: 'hull' missing")?;
    let hull = tpt_yard::tpt_yard_hull::HullGeometry {
        loa_m: num(hull_v, "loa_m")?,
        boa_m: num(hull_v, "boa_m")?,
        depth_m: num(hull_v, "depth_m")?,
        areal_density_kg_m2: num(hull_v, "areal_density_kg_m2")?,
        depth_bands: hull_v
            .get("depth_bands")
            .and_then(|n| n.as_u64())
            .ok_or("manifest: 'depth_bands' missing")? as u32,
    };
    let yard = v.get("yard_capabilities").ok_or("manifest: 'yard_capabilities' missing")?;
    let crane_kn = num(yard, "crane_capacity_kn")?;
    let ws = yard.get("workshop").ok_or("manifest: 'workshop' missing")?;
    let workshop = tpt_yard::tpt_yard_core::Dimensions::new(
        num(ws, "length_m")?,
        num(ws, "breadth_m")?,
        num(ws, "depth_m")?,
    );

    // 1. Block division.
    let construction = tpt_yard::tpt_yard_hull::HullConstruction::new(hull.clone());
    let blocks = construction.block_division(crane_kn, workshop);
    if blocks.is_empty() {
        return Err("block division produced no blocks (depth_bands == 0?)".into());
    }

    // 2. Erection order.
    let joins = construction.erection_sequence(&blocks);

    // 3. Lift check for the heaviest block (4-point pick at its corners).
    let heaviest = blocks
        .iter()
        .max_by(|a, b| a.weight_kg.total_cmp(&b.weight_kg))
        .expect("non-empty");
    let (hw, hd) = (heaviest.dimensions().length / 2.0, heaviest.dimensions().breadth / 2.0);
    let c = heaviest.geometry.centre;
    let lift_points = [
        Vector3::new(c.x - hw, c.y - hd, 0.0),
        Vector3::new(c.x + hw, c.y - hd, 0.0),
        Vector3::new(c.x + hw, c.y + hd, 0.0),
        Vector3::new(c.x - hw, c.y + hd, 0.0),
    ];
    let solver = tpt_yard::tpt_yard_structural::ConstructionStructuralSolver::new(
        tpt_yard::tpt_yard_structural::PartialStructure::default(),
        355.0,
    );
    let lift = solver
        .lifting_analysis(
            &tpt_yard::tpt_yard_structural::LiftableBody {
                mass_properties: MassProperties {
                    mass_kg: heaviest.weight_kg,
                    cog: heaviest.cog,
                },
            },
            crane_kn, // sling capacity tracks the crane
            crane_kn, // single-crane pick
            &lift_points,
            4.0,
        )
        .map_err(|e| format!("lift check: {e}"))?;

    // 4. Schedule: one erection activity per block, in erection order.
    let acts: Vec<tpt_yard_core::AssemblyActivity> = joins
        .iter()
        .map(|j| {
            let block = blocks
                .iter()
                .find(|b| b.id == j.block)
                .expect("join references a block");
            let deps: Vec<tpt_yard::tpt_yard_assembly::ActivityId> = j
                .onto
                .map(|onto| {
                    joins
                        .iter()
                        .position(|x| x.block == onto)
                        .map(|pos| tpt_yard::tpt_yard_assembly::ActivityId(pos as u64 + 1))
                        .into_iter()
                        .collect()
                })
                .unwrap_or_default();
            tpt_yard_core::AssemblyActivity::new(
                tpt_yard::tpt_yard_assembly::ActivityId(j.sequence_index as u64 + 1),
                format!("erect {}", block.name),
                tpt_yard_core::ActivityType::JoinBlock,
                8.0,
            )
            .with_dependencies(&deps)
        })
        .collect();
    let scheduler = tpt_yard::tpt_yard_scheduling::ShipyardScheduler::new(acts);
    let early = scheduler
        .optimize_sequence(tpt_yard::tpt_yard_scheduling::ScheduleObjective::MinimizeDuration)
        .map_err(|e| format!("schedule: {e}"))?;
    let levelled = scheduler
        .resource_leveling()
        .map_err(|e| format!("levelling: {e}"))?;
    let cp = scheduler.critical_path().map_err(|e| format!("critical path: {e}"))?;

    // 5. Report.
    if json_mode {
        println!(
            "{{\"blocks\":{},\"n_joins\":{},\"heaviest_block_kg\":{:.0},\"lift_safe\":{},\"makespan_h\":{:.1},\"levelled_makespan_h\":{:.1},\"critical_path_len\":{}}}",
            blocks.len(),
            joins.len(),
            heaviest.weight_kg,
            lift.safe,
            early.makespan_hours,
            levelled.makespan_hours,
            cp.len()
        );
        return Ok(());
    }
    let total_steel: f64 = blocks.iter().map(|b| b.weight_kg).sum();
    println!("Construction plan for {}", v.get("vessel").and_then(|x| x.as_str()).unwrap_or(path));
    println!("======================================================");
    println!("1. Block division: {} blocks, {:.0} t total steel", blocks.len(), total_steel / 1000.0);
    println!("2. Erection order: {} joins; first block on the dock floor, tiers bottom-up", joins.len());
    println!(
        "3. Lift check (heaviest block {:.0} t, 4-point pick): {}",
        heaviest.weight_kg / 1000.0,
        if lift.safe { "SAFE" } else { "UNSAFE" }
    );
    for n in &lift.notes {
        println!("   - {n}");
    }
    println!(
        "4. Schedule: makespan {:.1} h (levelled {:.1} h), critical path {} activities",
        early.makespan_hours, levelled.makespan_hours, cp.len()
    );
    println!("5. Drydock/launch: run the drydock and launch crates on the launch weight for the float-out plan");
    Ok(())
}

// ---------------------------------------------------------------- schedule

fn schedule(path: &str, json_mode: bool) -> Result<(), String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let v = Value::parse(&text).map_err(|e| format!("{path}: {e}"))?;
    let project = tpt_yard_core::VesselProject::from_json_value(&v)
        .map_err(|e| format!("{path}: {e}"))?;
    let acts: Vec<tpt_yard_core::AssemblyActivity> = project
        .build_phases
        .iter()
        .flat_map(|p| p.activities.iter().cloned())
        .collect();
    if acts.is_empty() {
        return Err("project has no activities to schedule".into());
    }
    let scheduler = tpt_yard::tpt_yard_scheduling::ShipyardScheduler::new(acts);
    let cp = scheduler.critical_path().map_err(|e| format!("{e}"))?;
    let levelled = scheduler.resource_leveling().map_err(|e| format!("{e}"))?;
    if json_mode {
        println!(
            "{{\"critical_path\":[{}],\"makespan_h\":{:.1}}}",
            cp.iter()
                .map(|a| a.0.to_string())
                .collect::<Vec<_>>()
                .join(","),
            levelled.makespan_hours
        );
        return Ok(());
    }
    println!(
        "Critical path: {} ({} activities), levelled makespan {:.1} h",
        cp.iter()
            .map(|a| format!("A{}", a.0))
            .collect::<Vec<_>>()
            .join(" -> "),
        cp.len(),
        levelled.makespan_hours
    );
    Ok(())
}

// ------------------------------------------------------------------ report

fn report(path: &str, json_mode: bool) -> Result<(), String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("reading {path}: {e}"))?;
    let v = Value::parse(&text).map_err(|e| format!("{path}: {e}"))?;
    let project = tpt_yard_core::VesselProject::from_json_value(&v)
        .map_err(|e| format!("{path}: {e}"))?;
    let twin = tpt_yard::tpt_yard_digital_twin::DigitalTwin::new(project);
    let report = twin.weight_model().weight_report();
    let check = twin.structural_check();
    if json_mode {
        println!(
            "{{\"design_kg\":{:.1},\"best_estimate_kg\":{:.1},\"margin_kg\":{:.1},\"structural_passed\":{}}}",
            report.design_weight_kg, report.total_weight_kg, report.margin_kg, check.passed
        );
        return Ok(());
    }
    println!("Project report: {}", twin.vessel.name);
    println!("  design weight   {:>10.0} kg", report.design_weight_kg);
    println!("  best estimate   {:>10.0} kg", report.total_weight_kg);
    println!("  growth margin   {:>10.0} kg", report.margin_kg);
    println!(
        "  structural check at start: {}",
        if check.passed { "passed" } else { "FAILED" }
    );
    Ok(())
}

// --------------------------------------------------------------------- new

fn new(rest: &[&str], json_mode: bool) -> Result<(), String> {
    let kind = rest.first().copied().ok_or(
        "new needs a kind: sea|space, or a template: container-ship|submarine|orbital-truss|habitat|solar-array",
    )?;
    // Named project templates (review 7F).
    if matches!(
        kind,
        "container-ship" | "submarine" | "orbital-truss" | "habitat" | "solar-array"
    ) {
        return template(kind, rest.get(1).copied(), json_mode);
    }
    let (phases, vessel, method, name): (Vec<tpt_yard_core::BuildPhase>, tpt_yard_core::VesselType, _, String) =
        match kind {
            "sea" => {
                let mut phase = tpt_yard_core::BuildPhase::new(tpt_yard_core::PhaseId(1), "Erection", 8.0);
                for i in 1..=4u64 {
                    let deps: Vec<tpt_yard::tpt_yard_assembly::ActivityId> = if i == 1 {
                        vec![]
                    } else {
                        vec![tpt_yard::tpt_yard_assembly::ActivityId(i - 1)]
                    };
                    phase.activities.push(
                        tpt_yard_core::AssemblyActivity::new(
                            tpt_yard::tpt_yard_assembly::ActivityId(i),
                            format!("Erect block {i}"),
                            tpt_yard_core::ActivityType::JoinBlock,
                            8.0,
                        )
                        .with_dependencies(&deps),
                    );
                }
                phase.weight_state = tpt_yard_core::WeightState {
                    design_kg: 4_000_000.0,
                    installed_kg: 0.0,
                };
                (
                    vec![phase],
                    tpt_yard_core::VesselType::Sea(tpt_yard_core::SeaVesselType::ContainerShip { teu_capacity: 800 }),
                    tpt_yard_core::ConstructionMethod::SeaDrydock,
                    rest.get(1).copied().unwrap_or("New sea vessel").to_string(),
                )
            }
            "space" => {
                let mut phase = tpt_yard_core::BuildPhase::new(tpt_yard_core::PhaseId(1), "Orbital assembly", 12.0);
                for i in 1..=3u64 {
                    phase.activities.push(tpt_yard_core::AssemblyActivity::new(
                        tpt_yard::tpt_yard_assembly::ActivityId(i),
                        format!("Install module {i}"),
                        tpt_yard_core::ActivityType::JoinBlock,
                        10.0,
                    ));
                }
                phase.weight_state = tpt_yard_core::WeightState {
                    design_kg: 150_000.0,
                    installed_kg: 0.0,
                };
                (
                    vec![phase],
                    tpt_yard_core::VesselType::Space(tpt_yard_core::SpaceVesselType::SpaceStation { modules: 3 }),
                    tpt_yard_core::ConstructionMethod::OrbitalAssembly,
                    rest.get(1).copied().unwrap_or("New space vessel").to_string(),
                )
            }
            other => return Err(format!("unknown kind '{other}' (expected sea|space)")),
        };
    let project = tpt_yard_core::VesselProject::new(
        tpt_yard_core::ProjectId(1),
        name,
        vessel,
        method,
        phases,
    )
    .ok_or("scaffold failed validation")?;
    let json = project.to_json().to_string_pretty();
    if json_mode {
        println!("{json}");
    } else {
        println!("Scaffolded project (save as project.json and run `tpt-yard validate project.json`):");
        println!("{json}");
    }
    Ok(())
}


/// Scaffold one of the named reference templates. Each template mirrors the
/// matching reference case in `test-data/` so the numbers are realistic.
fn template(kind: &str, name: Option<&str>, json_mode: bool) -> Result<(), String> {
    use tpt_yard::tpt_yard_assembly::ActivityId;
    let mut next_activity = 1u64;
    let mut mk = |idx: u64, phase_name: &str, days: f64, design_kg: f64, acts: &[(&str, f64)]| {
        let mut phase = tpt_yard_core::BuildPhase::new(tpt_yard_core::PhaseId(idx), phase_name, days);
        let base = next_activity;
        for (i, (n, h)) in acts.iter().enumerate() {
            let id = ActivityId(base + i as u64);
            let deps: Vec<ActivityId> = if i == 0 { vec![] } else { vec![ActivityId(base + i as u64 - 1)] };
            phase
                .activities
                .push(tpt_yard_core::AssemblyActivity::new(id, *n, tpt_yard_core::ActivityType::JoinBlock, *h).with_dependencies(&deps));
        }
        phase.weight_state = tpt_yard_core::WeightState {
            design_kg,
            installed_kg: 0.0,
        };
        next_activity += acts.len() as u64;
        phase
    };
    let (name, vessel, method, phases) = match kind {
        "container-ship" => (
            name.unwrap_or("Container ship 1400 TEU").to_string(),
            tpt_yard_core::VesselType::Sea(tpt_yard_core::SeaVesselType::ContainerShip { teu_capacity: 1400 }),
            tpt_yard_core::ConstructionMethod::SeaDrydock,
            vec![
                mk(1, "Steel prefabrication", 28.0, 4_000_000.0, &[("Cut steel", 8.0), ("Form panels", 8.0)]),
                mk(2, "Block assembly", 21.0, 2_000_000.0, &[("Assemble blocks", 16.0)]),
                mk(3, "Dock erection", 30.0, 1_500_000.0, &[("Erect tier 0", 8.0), ("Erect tier 1", 8.0)]),
                mk(4, "Outfitting & launch", 25.0, 900_000.0, &[("Outfit", 8.0), ("Launch", 4.0)]),
            ],
        ),
        "submarine" => (
            name.unwrap_or("Submarine pressure hull").to_string(),
            tpt_yard_core::VesselType::Sea(tpt_yard_core::SeaVesselType::Submarine {
                hull_type: tpt_yard_core::HullType::DoubleHull,
            }),
            tpt_yard_core::ConstructionMethod::SeaBlockConstruction,
            vec![mk(1, "Pressure hull sections", 40.0, 2_300_000.0, &[
                ("Roll and weld sections", 12.0), ("Fit ring stiffeners", 10.0), ("Hydro test", 6.0),
            ])],
        ),
        "orbital-truss" => (
            name.unwrap_or("ISS-class truss").to_string(),
            tpt_yard_core::VesselType::Space(tpt_yard_core::SpaceVesselType::SpaceStation { modules: 5 }),
            tpt_yard_core::ConstructionMethod::OrbitalAssembly,
            vec![mk(1, "On-orbit truss assembly", 45.0, 7_500.0, &[
                ("Deploy bay 1", 6.0), ("Deploy bay 2", 6.0), ("Deploy bay 3", 6.0),
            ])],
        ),
        "habitat" => (
            name.unwrap_or("Stanford torus habitat").to_string(),
            tpt_yard_core::VesselType::Space(tpt_yard_core::SpaceVesselType::SpaceStation { modules: 8 }),
            tpt_yard_core::ConstructionMethod::InSpaceManufacturing,
            vec![mk(1, "Habitat construction", 120.0, 10_000_000.0, &[
                ("Print ring sections", 24.0), ("Close the ring", 16.0), ("Spin-up checkout", 8.0),
            ])],
        ),
        "solar-array" => (
            name.unwrap_or("Space solar array").to_string(),
            tpt_yard_core::VesselType::Space(tpt_yard_core::SpaceVesselType::SpaceStation { modules: 2 }),
            tpt_yard_core::ConstructionMethod::InSpaceManufacturing,
            vec![mk(1, "Array manufacture", 30.0, 12_000.0, &[
                ("Print substrate", 12.0), ("Lay cells", 10.0), ("Deploy & verify", 6.0),
            ])],
        ),
        other => return Err(format!("unknown template '{other}'")),
    };
    let project = tpt_yard_core::VesselProject::new(tpt_yard_core::ProjectId(1), name, vessel, method, phases)
        .ok_or("template failed validation")?;
    println!("{}", project.to_json().to_string_pretty());
    if !json_mode {
        eprintln!("(save as project.json, then `tpt-yard validate project.json`)");
    }
    Ok(())
}
